### ISSUE TITLE
Eliminate usage of Detox's client.ws

### ISSUE THREAD

**Issue by d4vidi** [ouihealth/detox-puppeteer#15]
Hi @awinograd,

In the driver's implementation, the Detox Client's internal `ws` is used in order to communicate with the Chrome instance.
That was okay in older Detox versions, but in Detox 19 we no longer consider it a public property.
Would you consider reimplementing in a way more in the likes of our up-to-date plugin example? See [here](https://github.com/wix/Detox/blob/master/examples/demo-plugin/driver.js#L67)

**Comment by awinograd** [comment]
@d4vidi yes I'm happy to do this. I have pushed a change to master removing most of the internal ws class usage. I still rely on a private property of the client class since your change adding `.open()` to the public API has not yet been released. when that's out I can make the update on my end

**Comment by d4vidi** [comment]
Amazing! It should be released soon. Will keep you posted 👍🏻

**Comment by d4vidi** [comment]
@awinograd open is available now in latest Detox - [v19.3.1](https://github.com/wix/Detox/releases/tag/19.3.1)

**Comment by awinograd** [comment]
This update is released in 4.1.6

**Comment by d4vidi** [comment]
🚀

**Comment by awinograd** [comment]
@d4vidi I ran into an issue updating to use the new public API. Relevant context is in this commit message: https://github.com/ouihealth/detox-puppeteer/commit/dd6f301d4212a195935be96e4cdea1a231b7afe7.

It looks like the client class assumes it's being used as part of the tester vs an app (which makes sense since my plugin is likely the only js based client). Any ideas on what the best path forward is here? Should detox-puppeteer implement it's own `Client`? Or does it make sense for detox to update Client to be role agnostic when connecting?
